version: "3.9"

services:
  db:
    container_name: be_soc_net_postgres
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - 5439:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data_soc/

volumes:
  postgres_data:
